### ISSUE TITLE
Add step by step readme

### ISSUE THREAD

**Issue by pepoviola** [pepoviola/zombie-bite#2]

**Comment by kianenigma** [comment]
Yes please :)

**Comment by kianenigma** [comment]
and move the repo to paritytech?

**Comment by pepoviola** [comment]
> and move the repo to paritytech?

Yes, that my goal ones reach the desired functionalities (fork works for relaychain/system parachains). 

Thanks for the feedback 🙌

**Comment by pepoviola** [comment]
Closing here, steps are now in the readme.
Thx!
